### ISSUE TITLE
error pushing database

### ISSUE THREAD

**Issue by vivek7156** [mendsalbert/zero-to-hero#1]
error: permission denied for schema public
    at file:///D:/Projects/waste-manager/node_modules/@neondatabase/serverless/index.mjs:1345:74
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.query (D:\Projects\waste-manager\node_modules\drizzle-kit\bin.cjs:71972:26)
    at async pgPush (D:\Projects\waste-manager\node_modules\drizzle-kit\bin.cjs:74835:13)
    at async Object.handler (D:\Projects\waste-manager\node_modules\drizzle-kit\bin.cjs:83713:9)
    at async run (D:\Projects\waste-manager\node_modules\drizzle-kit\bin.cjs:82064:7) {
  length: 99,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: '28',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'aclchk.c',
  line: '2807',
  routine: 'aclcheck_error'
}

**Comment by mendsalbert** [comment]
@vivek7156 That has to do with your connection string. Kindly review it and make sure it correct

**Comment by vivek7156** [comment]
Thankyou, I used wrong one.
